name: Weekly Update Lotto

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  update-lotto:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.MY_TOKEN }}
      
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Run Script Without Repo Dependencies
      run: |
        mkdir temp
        cd temp
        npm init -y
        npm install axios @octokit/rest@20.0.2 node-fetch@2
        node ../server/weekly_lotto_action.js

    - name: Run Node.js Script
      run: node server/weekly_lotto_action.js