name: Weekly Update Lotto

on:
  schedule:
    - cron: "45 11 * * 6"   # 20:45 KST
    - cron: "0 12 * * 6"    # 21:00 KST
    - cron: "15 12 * * 6"   # 21:15 KST
    - cron: "30 12 * * 6"   # 21:30 KST
    - cron: "45 12 * * 6"   # 21:45 KST
    - cron: "0 13 * * 6"    # 22:00 KST

jobs:
  update-lotto:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.MY_TOKEN }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.MY_TOKEN }}

    - name: Set Up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: |
        npm install axios --legacy-peer-deps
        npm install @octokit/rest@20.0.2 --legacy-peer-deps
        npm install node-fetch@2 --legacy-peer-deps

    - name: Run Node.js Script
      run: node server/weekly_lotto_action.js

    - name: Update version.md with current date
      run: |
        TODAY=$(TZ=Asia/Seoul date +"%Y-%m-%d %H:%M:%S KST")
        echo "Last Update: $TODAY" > version.md

    - name: Sleep before commit & push
      run: sleep 100

    - name: Commit and Push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        git add version.md

        if ! git diff --cached --quiet; then
          git commit -m "Update version.md on $(date '+%Y-%m-%d %H:%M:%S')"

          # 최신 리모트 변경사항 가져오기
          git pull --rebase origin main

          # 푸시
          git push https://x-access-token:${{ secrets.MY_TOKEN }}@github.com/${{ github.repository }}.git
        else
          echo "No changes to commit"
        fi

